source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'
use_frameworks!


project 'Bamboo/Bamboo.xcodeproj'

target 'Bamboo' do
      pod 'AliyunOSSiOS'
      pod 'IQKeyboardManager'
      pod 'Bugly'
      pod 'mob_pushsdk'
end
